import '@/app/globals.css'; // Assuming @ is aliased to src/

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* Persistent Header/Navbar */}
        <header className="fixed top-6 left-1/2 z-50 -translate-x-1/2 w-[90vw] max-w-4xl rounded-full bg-white/80 backdrop-blur-md flex items-center px-6 min-h-[66px] border border-gray-200">
          {/* Logo */}
          <div className="flex items-center justify-center h-full">
            <img src="/adamasslogo.png" alt="Adamass Logo" className="h-5 w-auto -mt-1" />
          </div>
          {/* Menu Links */}
          <nav className="hidden md:flex flex-1 justify-center gap-14 text-gray-700 text-lg font-normal tracking-tight items-center">
            <a href="#home" className="hover:text-blue-600 transition">Home</a>
            <a href="#pricing" className="hover:text-blue-600 transition">Pricing</a>
            <a href="#faq" className="hover:text-blue-600 transition">FAQ</a>
          </nav>
          {/* Right Side Buttons */}
          <div className="flex items-center gap-2">
            <a href="#signin" className="px-5 py-2 rounded-full bg-white border border-gray-300 text-gray-700 hover:bg-gray-50 transition text-base font-normal">Sign in</a>
            <a href="#get-started" className="px-5 py-2 rounded-full bg-blue-600 text-white hover:bg-blue-700 transition text-base font-semibold shadow">Get started</a>
          </div>
        </header>
        <div className="pt-12">{children}</div>
      </body>
    </html>
  )
}
